#! /bin/sh
#Ref: lecture video

case "$1" in
  start)
    echo "Start aesdsocket server"
    start-stop-daemon -S -n aesdsocket -a /usr/bin/aesdsocket
    ;;
  stop)
    echo "Stop aesdsocket server"
    start-stop-daemon -K -n aesdsocket
    ;;
  *)
    echo "Usage: $0 {start|stop}"
  exit 1
esac

exit 0

